# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: Default

steps:
- script: node --version
  displayName: 'node version'

- script: npm --version
  displayName: 'npm version'

- script: npm install
  displayName: 'npm install'

- script: npm run test **/*.js
  displayName: 'npm test'